version: '3.8'

services:
  php:
    container_name: php
    image: sneezh/php-8:latest
    volumes:
      - ./:/var/www/html:cached
      - ./volumes/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./volumes/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
      - ./volumes/php/conf.d/docker-php-ext-rdkafka.ini:/usr/local/etc/php/conf.d/docker-php-ext-rdkafka.ini:delegated
    environment:
      XDEBUG_CONFIG: remote_host=${DEBUG_REMOTE_HOST} remote_port=${DEBUG_REMOTE_PORT} remote_enable=1 idekey=${DEBUG_IDEKEY}
      PHP_IDE_CONFIG: serverName=${DEBUG_SERVER_NAME}
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./volumes/nginx:/etc/nginx
      - ./var/log/nginx:/var/log/nginx
      - ./:/var/www/html
    ports:
      - ${NGINX_PORT}:80
    tty: true
    depends_on:
      - php
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/db-files
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.103:${KAFKA_PORT}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper