imports:
    - { resource: layer/domain.yaml }
    - { resource: layer/application.yaml }ยก
    - { resource: layer/infrastructure.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true