services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Domain\:
        resource: '../../src/Domain/*'

    # -------------------------------
    # Repository
    # -------------------------------
    App\Domain\Task\Repository\TaskRepositoryInterface: '@App\Application\Repository\TaskRepository'