framework:
    serializer:
        enabled: true

parameters:
    messenger.exceptions_to_log_levels:
        \InvalidArgumentException: !php/const Psr\Log\LogLevel::NOTICE

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Infrastructure\:
        resource: '../../src/Infrastructure/*'
        exclude: '../../src/Infrastructure/{DependencyInjection,Migrations,Kernel.php}'

    App\Infrastructure\Controller\:
        resource: '../../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

